coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 60%
comment:
  layout: "reach,diff,flags,files"
  behavior: default

ignore:
  - "clock/src/images/**/*"
  - "clock/src/sounds/**/*"
  - "**/*.css"
  - "**/*.svg"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.mp3"
