version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clock-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i1ogq2fvdxb8"
s3_prefix = "clock-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
