import { AvailableMatches } from "../types";

export default {
  441804: {
    players: {
      103: [
        {
          id: 1001,
          number: 12,
          name: "Jóhann Þór Vilhjálmsson",
          role: "Markmaður",
          show: true,
        },
        {
          id: 1002,
          number: 4,
          name: "Grímur Garri Sverrisson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1003,
          number: 7,
          name: "Elmar Logi Þeránarson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1004,
          number: 10,
          name: "Björgvin Haukur Bjarnason",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1005,
          number: 11,
          name: "Andri Sæberg Diego",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1006,
          number: 17,
          name: "Halldór Ingi Óskarsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1007,
          number: 20,
          name: "Ari Jóhannesson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1008,
          number: 22,
          name: "Pétur Mikael Magnússon",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1009,
          number: 28,
          name: "Arnar Ingason",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1010,
          number: 42,
          name: "Hallgeir Kári Kjartansson",
          role: "Fyrirliði",
          show: true,
        },
        {
          id: 1011,
          number: 59,
          name: "Tómas Þórisson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 1012,
          number: 18,
          name: "Tómas Eiríksson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 1013,
          number: 40,
          name: "Matthías Ævar Magnússon",
          role: "Varamaður",
          show: false,
        },
        {
          id: 1014,
          number: 45,
          name: "Jón Stefán Friðriksson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 1015,
          number: 53,
          name: "Andri Már Tryggvason",
          role: "Varamaður",
          show: false,
        },
        {
          id: 1016,
          number: 55,
          name: "Kári Karl Atlason",
          role: "Varamaður",
          show: false,
        },
        {
          id: 1017,
          number: null,
          name: "Aðalsteinn Aðalsteinsson",
          role: "Þjálfari",
          show: false,
        },
        {
          id: 1018,
          number: null,
          name: "Björn Bjartmarz",
          role: "Þjálfari",
          show: false,
        },
      ],
      203: [
        {
          id: 2001,
          number: 54,
          name: "Adam Ingi Benediktsson",
          role: "Markmaður",
          show: true,
        },
        {
          id: 2002,
          number: 5,
          name: "Ívar Orri Gissurarson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2003,
          number: 8,
          name: "Breki Muntaga Jallow",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2004,
          number: 12,
          name: "Tristan A. Castaneda Bjarnarson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2005,
          number: 20,
          name: "Aðalsteinn Einir L Kristinsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2006,
          number: 22,
          name: "Eiður Atli Rúnarsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2007,
          number: 24,
          name: "Patrik Hermannsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2008,
          number: 29,
          name: "Ari Sigurpálsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2009,
          number: 33,
          name: "Erik Hallgrímsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2010,
          number: 50,
          name: "Valdimar Einarsson",
          role: "Fyrirliði",
          show: true,
        },
        {
          id: 2011,
          number: 88,
          name: "Helgi Már Önnuson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 2012,
          number: 15,
          name: "Aron Óli Burrell",
          role: "Varamaður",
          show: false,
        },
        {
          id: 2013,
          number: 19,
          name: "Andri Már Harðarson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 2014,
          number: 45,
          name: "Konrád Elí Kjartansson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 2015,
          number: null,
          name: "Þórhallur Dan Jóhannsson",
          role: "Þjálfari",
          show: false,
        },
      ],
    },
    group: "3. flokkur",
  },
  441951: {
    players: {
      103: [
        {
          id: 3001,
          number: 1,
          name: "Jóhann Borg Kristjánsson",
          role: "Markmaður",
          show: true,
        },
        {
          id: 3002,
          number: 13,
          name: "Jóhannes Einarsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3003,
          number: 16,
          name: "Jóel Kristjánsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3004,
          number: 33,
          name: "Jóhannes Karl Bárðarson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3005,
          number: 34,
          name: "Stefán Steinsen",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3006,
          number: 38,
          name: "Bjarki Hall",
          role: "Fyrirliði",
          show: true,
        },
        {
          id: 3007,
          number: 40,
          name: "Matthías Ævar Magnússon",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3008,
          number: 45,
          name: "Jón Stefán Friðriksson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3009,
          number: 50,
          name: "Arnar Már Ásmundsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3010,
          number: 53,
          name: "Andri Már Tryggvason",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3011,
          number: 55,
          name: "Kári Karl Atlason",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 3012,
          number: 31,
          name: "Benedikt Ernir Magnússon",
          role: "Varamaður",
          show: false,
        },
        {
          id: 3013,
          number: 35,
          name: "Ýmir Hugi Ágústsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 3014,
          number: 36,
          name: "Brimar Ólafsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 3015,
          number: 43,
          name: "Gunnar Magnús Sch Thorsteinsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 3016,
          number: 51,
          name: "Ólafur Örn Olafsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 3017,
          number: null,
          name: "Aðalsteinn Aðalsteinsson",
          role: "Þjálfari",
          show: false,
        },
        {
          id: 3018,
          number: null,
          name: "Björn Bjartmarz",
          role: "Þjálfari",
          show: false,
        },
        {
          id: 3019,
          number: 8,
          name: "Róbert Hao Nguyen",
          role: "Varamarkmaður",
          show: false,
        },
      ],
      203: [
        {
          id: 4001,
          number: 1,
          name: "Ólafur Örn Ásgeirsson",
          role: "Markmaður",
          show: true,
        },
        {
          id: 4002,
          number: 7,
          name: "Alexander Pálmi Ólafsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4003,
          number: 11,
          name: "Stephan Briem",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4004,
          number: 19,
          name: "Andri Már Harðarson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4005,
          number: 19,
          name: "Reynir Örn Guðmundsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4006,
          number: 24,
          name: "Hrannar Þór Eðvarðsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4007,
          number: 25,
          name: "Marvin Jónasson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4008,
          number: 30,
          name: "Hákon Freyr Jónsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4009,
          number: 31,
          name: "Aron Jarl Davíðsson",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4010,
          number: 32,
          name: "Tristan Þór Traustason",
          role: "Leikmaður",
          show: true,
        },
        {
          id: 4011,
          number: 4,
          name: "Bjarni Valur Valdimarsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 4012,
          number: 7,
          name: "Ísak Daði Henrysson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 4013,
          number: 18,
          name: "Jökull Jónsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 4014,
          number: 45,
          name: "Konrád Elí Kjartansson",
          role: "Fyrirliði",
          show: true,
        },
        {
          id: 4015,
          number: 55,
          name: "Tristan Dúi Kjartansson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 4016,
          number: 99,
          name: "Valgeir Steinn Gunnarsson",
          role: "Varamaður",
          show: false,
        },
        {
          id: 4017,
          number: null,
          name: "Jakob Hallgeirsson",
          role: "Þjálfari",
          show: false,
        },
      ],
    },
    group: "3. flokkur B lið",
  },
} as AvailableMatches;
