import { Roster } from "../types";

export default {
  home: [
    {
      id: 1001,
      number: 12,
      name: "Jóhann Þór Vilhjálmsson",
      role: "Markmaður",
      show: true,
    },
    {
      id: 1002,
      number: 4,
      name: "Grímur Garri Sverrisson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1003,
      number: 7,
      name: "Elmar Logi Þeránarson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1004,
      number: 10,
      name: "Björgvin Haukur Bjarnason",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1005,
      number: 11,
      name: "Andri Sæberg Diego",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1006,
      number: 17,
      name: "Halldór Ingi Óskarsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1007,
      number: 20,
      name: "Ari Jóhannesson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1008,
      number: 22,
      name: "Pétur Mikael Magnússon",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1009,
      number: 28,
      name: "Arnar Ingason",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1010,
      number: 42,
      name: "Hallgeir Kári Kjartansson",
      role: "Fyrirliði",
      show: true,
    },
    {
      id: 1011,
      number: 59,
      name: "Tómas Þórisson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 1012,
      number: 18,
      name: "Tómas Eiríksson",
      role: "Varamaður",
      show: false,
    },
    {
      id: 1013,
      number: 40,
      name: "Matthías Ævar Magnússon",
      role: "Varamaður",
      show: false,
    },
    {
      id: 1014,
      number: 45,
      name: "Jón Stefán Friðriksson",
      role: "Varamaður",
      show: false,
    },
    {
      id: 1015,
      number: 53,
      name: "Andri Már Tryggvason",
      role: "Varamaður",
      show: false,
    },
    {
      id: 1016,
      number: 55,
      name: "Kári Karl Atlason",
      role: "Varamaður",
      show: false,
    },
    {
      id: 1017,
      number: null,
      name: "Aðalsteinn Aðalsteinsson",
      role: "Þjálfari",
      show: false,
    },
    {
      id: 1018,
      number: null,
      name: "Björn Bjartmarz",
      role: "Þjálfari",
      show: false,
    },
  ],
  away: [
    {
      id: 2001,
      number: 54,
      name: "Adam Ingi Benediktsson",
      role: "Markmaður",
      show: true,
    },
    {
      id: 2002,
      number: 5,
      name: "Ívar Orri Gissurarson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2003,
      number: 8,
      name: "Breki Muntaga Jallow",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2004,
      number: 12,
      name: "Tristan A. Castaneda Bjarnarson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2005,
      number: 20,
      name: "Aðalsteinn Einir L Kristinsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2006,
      number: 22,
      name: "Eiður Atli Rúnarsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2007,
      number: 24,
      name: "Patrik Hermannsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2008,
      number: 29,
      name: "Ari Sigurpálsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2009,
      number: 33,
      name: "Erik Hallgrímsson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2010,
      number: 50,
      name: "Valdimar Einarsson",
      role: "Fyrirliði",
      show: true,
    },
    {
      id: 2011,
      number: 88,
      name: "Helgi Már Önnuson",
      role: "Leikmaður",
      show: true,
    },
    {
      id: 2012,
      number: 15,
      name: "Aron Óli Burrell",
      role: "Varamaður",
      show: false,
    },
    {
      id: 2013,
      number: 19,
      name: "Andri Már Harðarson",
      role: "Varamaður",
      show: false,
    },
    {
      id: 2014,
      number: 45,
      name: "Konrád Elí Kjartansson",
      role: "Varamaður",
      show: false,
    },
    {
      id: 2015,
      number: null,
      name: "Þórhallur Dan Jóhannsson",
      role: "Þjálfari",
      show: false,
    },
  ],
} as Roster;
