/* eslint-disable global-require */
module.exports = {
  Portúgal: require("./club-logos/Portugal.svg"),
  "Dalvík 2": require("./club-logos/Dalvík 2.png"),
  "Dalvík-Reynir": require("./club-logos/Dalvík-Reynir.svg"),
  "Derby County": require("./club-logos/Derby County.png"),
  "Fjarðab-Höttur-Leiknir": require("./club-logos/Fjarðab-Höttur-Leiknir.svg"),
  "Geisli A": require("./club-logos/Geisli A.svg"),
  "HK-Víkingur": require("./club-logos/HK-Víkingur.svg"),
  "Hvíti riddarinn": require("./club-logos/Hvíti riddarinn.svg"),
  "Hörður P": require("./club-logos/Hörður P.svg"),
  "Hörður Í": require("./club-logos/Hörður Í.png"),
  "Höttur-Huginn": require("./club-logos/Höttur-Huginn.svg"),
  "Kormákur-Hvöt": require("./club-logos/Kormákur-Hvöt.svg"),
  "Leiknir F": require("./club-logos/Leiknir F.svg"),
  "Leiknir R": require("./club-logos/Leiknir R.svg"),
  "Neisti D": require("./club-logos/Neisti D.svg"),
  "Reynir S": require("./club-logos/Reynir S.svg"),
  "Snæfellsnes 2": require("./club-logos/Snæfellsnes 2.png"),
  "Vængir Júpiters": require("./club-logos/Vængir Júpiters.svg"),
  "Víkingur O": require("./club-logos/Víkingur O.svg"),
  "Víkingur R": require("./club-logos/Víkingur R.svg"),
  "Þróttur N": require("./club-logos/Þróttur N.svg"),
  "Þróttur R": require("./club-logos/Þróttur R.svg"),
  "Þróttur V": require("./club-logos/Þróttur V.svg"),
  "Þróttur-SR": require("./club-logos/Þróttur-SR.png"),
  "Þór Th": require("./club-logos/Þór Th.svg"),
  "Þór-KA": require("./club-logos/Þór-KA.svg"),
  Afríka: require("./club-logos/Afríka.svg"),
  Afturelding: require("./club-logos/Afturelding.svg"),
  Armenía: require("./club-logos/Armenia.svg"),
  Augnablik: require("./club-logos/Augnablik.svg"),
  Berserkir: require("./club-logos/Berserkir.svg"),
  Björninn: require("./club-logos/Björninn.png"),
  Breiðablik: require("./club-logos/Breiðablik.svg"),
  Dalvík: require("./club-logos/Dalvík.png"),
  Drangey: require("./club-logos/Drangey.svg"),
  Einherji: require("./club-logos/Einherji.svg"),
  Elliði: require("./club-logos/Elliði.svg"),
  FH: require("./club-logos/FH.svg"),
  Fenrir: require("./club-logos/Fenrir.png"),
  Fjarðabyggð: require("./club-logos/Fjarðabyggð.svg"),
  Fjölnir: require("./club-logos/Fjölnir.svg"),
  Fram: require("./club-logos/Fram.svg"),
  Fylkir: require("./club-logos/Fylkir.svg"),
  GG: require("./club-logos/GG.svg"),
  Gnúpverjar: require("./club-logos/Gnúpverjar.svg"),
  Grikkland: require("./club-logos/Grikkland.svg"),
  Grindavík: require("./club-logos/Grindavík.svg"),
  Grundarfjörður: require("./club-logos/Grundarfjörður.svg"),
  Grótta: require("./club-logos/Grótta.svg"),
  HK: require("./club-logos/HK.svg"),
  HSH: require("./club-logos/HSH.svg"),
  Hamar: require("./club-logos/Hamar.svg"),
  Hamrarnir: require("./club-logos/Hamrarnir.svg"),
  Haukar: require("./club-logos/Haukar.svg"),
  Hrunamenn: require("./club-logos/Hrunamenn.svg"),
  Huginn: require("./club-logos/Huginn.svg"),
  Hvöt: require("./club-logos/Hvöt.svg"),
  Höttur: require("./club-logos/Höttur.svg"),
  KA: require("./club-logos/KA.svg"),
  KB: require("./club-logos/KB.svg"),
  KF: require("./club-logos/KF.svg"),
  KFG: require("./club-logos/KFG.png"),
  KFR: require("./club-logos/KFR.svg"),
  KFS: require("./club-logos/KFS.svg"),
  KH: require("./club-logos/KH.svg"),
  KM: require("./club-logos/KM.png"),
  KR: require("./club-logos/KR.svg"),
  KV: require("./club-logos/KV.svg"),
  Kasakstan: require("./club-logos/Kasakstan.png"),
  Keflavík: require("./club-logos/Keflavík.svg"),
  Kjalnesingar: require("./club-logos/Kjalnesingar.svg"),
  Kormákur: require("./club-logos/Kormákur.svg"),
  Kría: require("./club-logos/Kría.svg"),
  KÁ: require("./club-logos/KÁ.png"),
  Kári: require("./club-logos/Kári.svg"),
  Kóngarnir: require("./club-logos/Kóngarnir.svg"),
  Kórdrengir: require("./club-logos/Kórdrengir.svg"),
  Léttir: require("./club-logos/Léttir.svg"),
  Lúxemborg: require("./club-logos/Luxembourg.svg"),
  Magni: require("./club-logos/Magni.svg"),
  Máni: require("./club-logos/Máni.svg"),
  Mídas: require("./club-logos/Mídas.svg"),
  Njarðvík: require("./club-logos/Njarðvík.svg"),
  Nökkvi: require("./club-logos/Nökkvi.svg"),
  RKV: require("./club-logos/RKV.png"),
  SR: require("./club-logos/SR.svg"),
  Samherjar: require("./club-logos/Samherjar.png"),
  Selfoss: require("./club-logos/Selfoss.svg"),
  Sindri: require("./club-logos/Sindri.svg"),
  Skallagrímur: require("./club-logos/Skallagrímur.svg"),
  Snæfell: require("./club-logos/Snæfell.svg"),
  Snæfellsnes: require("./club-logos/Snæfellsnes.png"),
  Spánn: require("./club-logos/Spánn.png"),
  Stjarnan: require("./club-logos/Stjarnan.png"),
  Stokkseyri: require("./club-logos/Stokkseyri.svg"),
  StálÚlfur: require("./club-logos/StálÚlfur.svg"),
  Svíðþjóð: require("./club-logos/Sweden.svg"),
  Tindastóll: require("./club-logos/Tindastóll.svg"),
  Valur: require("./club-logos/Valur.svg"),
  Vatnaliljur: require("./club-logos/Vatnaliljur.svg"),
  Vestri: require("./club-logos/Vestri.svg"),
  Víðir: require("./club-logos/Víðir.svg"),
  Völsungur: require("./club-logos/Völsungur.svg"),
  Álafoss: require("./club-logos/Álafoss.png"),
  Álftanes: require("./club-logos/Álftanes.svg"),
  Árborg: require("./club-logos/Árborg.svg"),
  Ármann: require("./club-logos/Ármann.png"),
  Ægir: require("./club-logos/Ægir.svg"),
  ÍA: require("./club-logos/ÍA.svg"),
  ÍBV: require("./club-logos/ÍBV.svg"),
  ÍH: require("./club-logos/ÍH.svg"),
  ÍR: require("./club-logos/ÍR.svg"),
  Írland: require("./club-logos/Írland.svg"),
  Ísbjörninn: require("./club-logos/Ísbjörninn.svg"),
  Ísland: require("./club-logos/Iceland.svg"),
  Ítalía: require("./club-logos/Italy.svg"),
  Örninn: require("./club-logos/Örninn.svg"),
  Úlfarnir: require("./club-logos/Úlfarnir.svg"),
  Ýmir: require("./club-logos/Ýmir.svg"),
  Þór: require("./club-logos/Þór.svg"),
};
