/* eslint-disable global-require */
module.exports = {
    Afríka: require('./club-logos/Afríka.svg'),
    Afturelding: require('./club-logos/Afturelding.svg'),
    Augnablik: require('./club-logos/Augnablik.svg'),
    Álafoss: require('./club-logos/Álafoss.svg'),
    Álftanes: require('./club-logos/Álftanes.svg'),
    Árborg: require('./club-logos/Árborg.svg'),
    Ármann: require('./club-logos/Ármann.png'),
    Berserkir: require('./club-logos/Berserkir.svg'),
    Björninn: require('./club-logos/Björninn.png'),
    Breiðablik: require('./club-logos/Breiðablik.svg'),
    'Dalvík-Reynir': require('./club-logos/Dalvík-Reynir.svg'),
    Drangey: require('./club-logos/Drangey.svg'),
    Einherji: require('./club-logos/Einherji.svg'),
    Elliði: require('./club-logos/Elliði.svg'),
    FH: require('./club-logos/FH.svg'),
    'Fjarðab-Höttur-Leiknir': require('./club-logos/Fjarðab-Höttur-Leiknir.svg'),
    Fjarðabyggð: require('./club-logos/Fjarðabyggð.svg'),
    Fjölnir: require('./club-logos/Fjölnir.svg'),
    Fram: require('./club-logos/Fram.svg'),
    Fylkir: require('./club-logos/Fylkir.svg'),
    'Geisli A': require('./club-logos/Geisli A.svg'),
    GG: require('./club-logos/GG.svg'),
    Gnúpverjar: require('./club-logos/Gnúpverjar.svg'),
    Grindavík: require('./club-logos/Grindavík.svg'),
    Grótta: require('./club-logos/Grótta.svg'),
    Grundarfjörður: require('./club-logos/Grundarfjörður.svg'),
    Hamar: require('./club-logos/Hamar.svg'),
    Hamrarnir: require('./club-logos/Hamrarnir.svg'),
    Haukar: require('./club-logos/Haukar.svg'),
    HK: require('./club-logos/HK.svg'),
    'HK-Víkingur': require('./club-logos/HK-Víkingur.svg'),
    Hrunamenn: require('./club-logos/Hrunamenn.svg'),
    HSH: require('./club-logos/HSH.svg'),
    Huginn: require('./club-logos/Huginn.svg'),
    'Hvíti riddarinn': require('./club-logos/Hvíti riddarinn.svg'),
    Hvöt: require('./club-logos/Hvöt.svg'),
    'Hörður Í': require('./club-logos/Hörður Í.png'),
    'Hörður P': require('./club-logos/Hörður P.svg'),
    Höttur: require('./club-logos/Höttur.svg'),
    ÍA: require('./club-logos/ÍA.svg'),
    ÍBV: require('./club-logos/ÍBV.svg'),
    ÍH: require('./club-logos/ÍH.svg'),
    ÍR: require('./club-logos/ÍR.svg'),
    Ísbjörninn: require('./club-logos/Ísbjörninn.svg'),
    KA: require('./club-logos/KA.svg'),
    Kári: require('./club-logos/Kári.svg'),
    KB: require('./club-logos/KB.svg'),
    Keflavík: require('./club-logos/Keflavík.svg'),
    KF: require('./club-logos/KF.svg'),
    KFG: require('./club-logos/KFG.png'),
    KFR: require('./club-logos/KFR.svg'),
    KFS: require('./club-logos/KFS.svg'),
    KH: require('./club-logos/KH.svg'),
    Kjalnesingar: require('./club-logos/Kjalnesingar.svg'),
    Kormákur: require('./club-logos/Kormákur.svg'),
    'Kormákur-Hvöt': require('./club-logos/Kormákur-Hvöt.svg'),
    Kóngarnir: require('./club-logos/Kóngarnir.svg'),
    Kórdrengir: require('./club-logos/Kórdrengir.svg'),
    KR: require('./club-logos/KR.svg'),
    Kría: require('./club-logos/Kría.svg'),
    KV: require('./club-logos/KV.svg'),
    'Leiknir F': require('./club-logos/Leiknir F.svg'),
    'Leiknir R': require('./club-logos/Leiknir R.svg'),
    Léttir: require('./club-logos/Léttir.svg'),
    Magni: require('./club-logos/Magni.svg'),
    Máni: require('./club-logos/Máni.svg'),
    Mídas: require('./club-logos/Mídas.svg'),
    'Neisti D': require('./club-logos/Neisti D.svg'),
    Njarðvík: require('./club-logos/Njarðvík.svg'),
    Nökkvi: require('./club-logos/Nökkvi.svg'),
    'Reynir S': require('./club-logos/Reynir S.svg'),
    Selfoss: require('./club-logos/Selfoss.svg'),
    Sindri: require('./club-logos/Sindri.svg'),
    Skallagrímur: require('./club-logos/Skallagrímur.svg'),
    Snæfell: require('./club-logos/Snæfell.svg'),
    SR: require('./club-logos/SR.svg'),
    'Stál-úlfur': require('./club-logos/Stál-úlfur.svg'),
    Stjarnan: require('./club-logos/Stjarnan.svg'),
    Stokkseyri: require('./club-logos/Stokkseyri.svg'),
    Tindastóll: require('./club-logos/Tindastóll.svg'),
    Úlfarnir: require('./club-logos/Úlfarnir.svg'),
    Valur: require('./club-logos/Valur.svg'),
    Vatnaliljur: require('./club-logos/Vatnaliljur.svg'),
    Vestri: require('./club-logos/Vestri.svg'),
    Víðir: require('./club-logos/Víðir.svg'),
    'Víkingur Ó': require('./club-logos/Víkingur Ó.svg'),
    'Víkingur R': require('./club-logos/Víkingur R.svg'),
    'Vængir Júpiters': require('./club-logos/Vængir Júpiters.svg'),
    Völsungur: require('./club-logos/Völsungur.svg'),
    Ýmir: require('./club-logos/Ýmir.svg'),
    Þór: require('./club-logos/Þór.svg'),
    'Þór Þ': require('./club-logos/Þór Þ.svg'),
    'Þór-KA': require('./club-logos/Þór-KA.svg'),
    'Þróttur N': require('./club-logos/Þróttur N.svg'),
    'Þróttur R': require('./club-logos/Þróttur R.svg'),
    'Þróttur V': require('./club-logos/Þróttur V.svg'),
    Ægir: require('./club-logos/Ægir.svg'),
    Örninn: require('./club-logos/Örninn.svg'),
};
