/* eslint-disable global-require */
module.exports = {
    Afríka: require("./club-logos/Afríka.svg"),
    Afturelding: require("./club-logos/Afturelding.png"),
    Augnablik: require("./club-logos/Augnablik.png"),
    Austri: require("./club-logos/Austri.png"),
    Álafoss: require("./club-logos/Álafoss.png"),
    Álftanes: require("./club-logos/Álftanes.svg"),
    Árborg: require("./club-logos/Árborg.svg"),
    Ármann: require("./club-logos/Ármann.png"),
    Berserkir: require("./club-logos/Berserkir.svg"),
    Björninn: require("./club-logos/Björninn.png"),
    "Boltaf. Norðfj": require("./club-logos/Boltaf. Norðfj.png"),
    Breiðablik: require("./club-logos/Breiðablik.svg"),
    Dalvík: require("./club-logos/Dalvík.png"),
    "Dalvík-Reynir": require("./club-logos/Dalvík-Reynir.svg"),
    Drangey: require("./club-logos/Drangey.svg"),
    Einherji: require("./club-logos/Einherji.png"),
    Elliði: require("./club-logos/Elliði.svg"),
    Fenrir: require("./club-logos/Fenrir.png"),
    FH: require("./club-logos/FH.svg"),
    "Fjarðab-Höttur-Leiknir": require("./club-logos/Fjarðab-Höttur-Leiknir.svg"),
    Fjarðabyggð: require("./club-logos/Fjarðabyggð.svg"),
    Fjölnir: require("./club-logos/Fjölnir.svg"),
    Fram: require("./club-logos/Fram.svg"),
    Fylkir: require("./club-logos/Fylkir.svg"),
    "Geisli A": require("./club-logos/Geisli A.svg"),
    GG: require("./club-logos/GG.png"),
    Gnúpverjar: require("./club-logos/Gnúpverjar.svg"),
    Grindavík: require("./club-logos/Grindavík.svg"),
    Grótta: require("./club-logos/Grótta.png"),
    Grundarfjörður: require("./club-logos/Grundarfjörður.svg"),
    Gullfálkinn: require("./club-logos/Gullfálkinn.png"),
    Hafnir: require("./club-logos/Hafnir.png"),
    Hamar: require("./club-logos/Hamar.svg"),
    Hamrarnir: require("./club-logos/Hamrarnir.svg"),
    Haukar: require("./club-logos/Haukar.svg"),
    HK: require("./club-logos/HK.svg"),
    "HK-Víkingur": require("./club-logos/HK-Víkingur.svg"),
    Hrunamenn: require("./club-logos/Hrunamenn.svg"),
    HSH: require("./club-logos/HSH.svg"),
    Huginn: require("./club-logos/Huginn.svg"),
    "Hvíti riddarinn": require("./club-logos/Hvíti riddarinn.svg"),
    Hvöt: require("./club-logos/Hvöt.svg"),
    "Hörður Í": require("./club-logos/Hörður Í.png"),
    "Hörður P": require("./club-logos/Hörður P.svg"),
    Höttur: require("./club-logos/Höttur.svg"),
    "Höttur-Huginn": require("./club-logos/Höttur-Huginn.svg"),
    ÍA: require("./club-logos/ÍA.svg"),
    ÍBV: require("./club-logos/ÍBV.png"),
    ÍH: require("./club-logos/ÍH.svg"),
    ÍR: require("./club-logos/ÍR.svg"),
    Ísbjörninn: require("./club-logos/Ísbjörninn.svg"),
    KA: require("./club-logos/KA.svg"),
    KÁ: require("./club-logos/KÁ.png"),
    Kári: require("./club-logos/Kári.svg"),
    KB: require("./club-logos/KB.png"),
    Keflavík: require("./club-logos/Keflavík.svg"),
    KF: require("./club-logos/KF.svg"),
    KFA: require("./club-logos/KFA.png"),
    KFB: require("./club-logos/KFB.png"),
    KFG: require("./club-logos/KFG.png"),
    KFK: require("./club-logos/KFK.png"),
    KFR: require("./club-logos/KFR.svg"),
    KFS: require("./club-logos/KFS.svg"),
    KH: require("./club-logos/KH.svg"),
    Kjalnesingar: require("./club-logos/Kjalnesingar.svg"),
    KM: require("./club-logos/KM.png"),
    Kormákur: require("./club-logos/Kormákur.svg"),
    "Kormákur-Hvöt": require("./club-logos/Kormákur-Hvöt.png"),
    Kóngarnir: require("./club-logos/Kóngarnir.svg"),
    Kórdrengir: require("./club-logos/Kórdrengir.svg"),
    KR: require("./club-logos/KR.svg"),
    Kría: require("./club-logos/Kría.png"),
    KS: require("./club-logos/KS.png"),
    KV: require("./club-logos/KV.svg"),
    "Leiknir F": require("./club-logos/Leiknir F.svg"),
    "Leiknir R": require("./club-logos/Leiknir R.svg"),
    Léttir: require("./club-logos/Léttir.png"),
    Magni: require("./club-logos/Magni.png"),
    Máni: require("./club-logos/Máni.svg"),
    Mídas: require("./club-logos/Mídas.png"),
    "Neisti D": require("./club-logos/Neisti D.svg"),
    Njarðvík: require("./club-logos/Njarðvík.svg"),
    Nökkvi: require("./club-logos/Nökkvi.svg"),
    RB: require("./club-logos/RB.png"),
    "Reynir H": require("./club-logos/Reynir H.png"),
    "Reynir S": require("./club-logos/Reynir S.svg"),
    RKV: require("./club-logos/RKV.png"),
    Samherjar: require("./club-logos/Samherjar.png"),
    Selfoss: require("./club-logos/Selfoss.svg"),
    Sindri: require("./club-logos/Sindri.svg"),
    Skallagrímur: require("./club-logos/Skallagrímur.svg"),
    Skandinavía: require("./club-logos/Skandinavía.png"),
    Smári: require("./club-logos/Smári.png"),
    Snæfell: require("./club-logos/Snæfell.svg"),
    Snæfellsnes: require("./club-logos/Snæfellsnes.png"),
    Spyrnir: require("./club-logos/Spyrnir.png"),
    SR: require("./club-logos/SR.svg"),
    StálÚlfur: require("./club-logos/StálÚlfur.svg"),
    Stjarnan: require("./club-logos/Stjarnan.png"),
    Stokkseyri: require("./club-logos/Stokkseyri.svg"),
    Tindastóll: require("./club-logos/Tindastóll.svg"),
    Uppsveitir: require("./club-logos/Uppsveitir.png"),
    Úlfarnir: require("./club-logos/Úlfarnir.png"),
    Valur: require("./club-logos/Valur.svg"),
    Vatnaliljur: require("./club-logos/Vatnaliljur.svg"),
    Vestri: require("./club-logos/Vestri.svg"),
    Víðir: require("./club-logos/Víðir.svg"),
    "Víkingur O": require("./club-logos/Víkingur O.svg"),
    "Víkingur R": require("./club-logos/Víkingur R.svg"),
    "Vængir Júpiters": require("./club-logos/Vængir Júpiters.svg"),
    Völsungur: require("./club-logos/Völsungur.svg"),
    Ýmir: require("./club-logos/Ýmir.svg"),
    Þór: require("./club-logos/Þór.png"),
    "Þór Th": require("./club-logos/Þór Th.svg"),
    "Þór-KA": require("./club-logos/Þór-KA.png"),
    "Þróttur N": require("./club-logos/Þróttur N.svg"),
    "Þróttur R": require("./club-logos/Þróttur R.svg"),
    "Þróttur V": require("./club-logos/Þróttur V.svg"),
    "Þróttur-SR": require("./club-logos/Þróttur-SR.png"),
    Ægir: require("./club-logos/Ægir.svg"),
    Örninn: require("./club-logos/Örninn.svg"),
};
